### ISSUE TITLE
Data and plot folders are too large

### ISSUE THREAD

**Issue by JoaoCarabetta** [mszell/bikenwgrowth#3] opened 2021-07-07 14:50 UTC
Super interesting work!

But, it is taking too long to clone it. It downloads 11GB of data :0

I recommend to gitignore the `data` and `plot` folders. That'd make it easier to clone the repo :)

**Comment by mszell** [comment] 2021-07-07 16:09
Hi, thanks! :)
Oh, I didnt realize it was that huge. I might still need to work with the data soon and have them part of the repo. I'll consider gitignoring the data and plots out later when the external data repository is established. For the next few weeks I'm not able to do much coding/github work though so patience please.. and thanks for the tip!

**Comment by mszell** [comment] 2021-12-03 13:55
Finally had time for this: https://github.com/mszell/bikenwgrowth/commit/0bd135246afd5cca46bfd4b678b0c08edcaa9fb5
Hope it's easier to fork now (if not let me know)

**Comment by mszell** [comment] 2021-12-10 22:14
That didn't fix it, I just cloned it.

Apparently the problem is that all the large files (11GB) are contained in the .git/objects folder, i.e. in the project history, so just gitignoring it doesn't get rid of the problem, neither does git repack or git gc or git prune, see: https://stackoverflow.com/questions/5613345/how-to-shrink-the-git-folder

This might work: https://stackoverflow.com/questions/3797907/how-to-remove-unused-objects-from-a-git-repository
I might run this at some point, when/if I have time to take precautions and to understand all the git stuff better to not mess up everything.

**Comment by mszell** [comment] 2024-09-06 12:47
Thx, partially resolved with a warning and solution to clone without history: https://github.com/mszell/bikenwgrowth/commit/c4712704232d334e0b75afca10654923d4f09063
Might make sense to do a deeper cleaning at some point in the future.

**Comment by anastassiavybornova** [comment] 2024-09-18 08:32
@mszell  can we close this issue for now?

**Closed** 2024-09-18 08:37 UTC
